[package]
name = "tenk"
version = "0.1.0"
authors = ["Willem Wyndham <willem@near.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = { git = "https://github.com/willemneal/near-sdk-rs", branch = "feat/nft_refund_option"}
near-contract-standards = { git = "https://github.com/willemneal/near-sdk-rs", branch = "feat/nft_refund_option"}
serde = "1.0.0"
contract-utils =  { path = "../contract-utils" }
near-units = { version = "0.2.0" }

[dev-dependencies]
rand = "0.7.2"
rand_xorshift = "0.2.0"
serde_json = "1.0.0"

[features]
default = []
mainnet = []
